language: php

php:
  - 5.2
  - 5.3

env:
  - DB=mysql

install:
  - pear channel-discover pear.phpunit.de
  - pear install pear.phpunit.de/PHPUnit
  - phpenv rehash

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS omeka_test;" -uroot; fi
  - mv application/config/config.ini.changeme application/config/config.ini
  - mv application/tests/config.ini.changeme application/tests/config.ini
  - sed -i 's/db.host = ""/db.host = "localhost"/' application/tests/config.ini
  - sed -i 's/db.username = ""/db.username = "root"/' application/tests/config.ini
  - sed -i 's/db.dbname = ""/db.dbname = "omeka_test"/' application/tests/config.ini
  - sed -i 's/paths.imagemagick = ""/paths.imagemagick = "\/usr\/bin\/"/' application/tests/config.ini

script: cd application/tests && phpunit
